config/routes.rb
Populinator::Application.routes.draw do

  devise_for :users
  resources :languages do
    resources :corpora
  end

  resources :settlements

  resources :beings

  root "welcome#index"
end

app/models/settlement.rb
class Settlement < ActiveRecord::Base
end

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
  before_action :set_settlement, only: [:show, :edit, :update, :destroy]

  # GET /settlements
  # GET /settlements.json
  def index
    @settlements = Settlement.all
  end

  # GET /settlements/1
  # GET /settlements/1.json
  def show
  end

  # GET /settlements/new
  def new
    @settlement = Settlement.new
  end

  # GET /settlements/1/edit
  def edit
  end

  # POST /settlements
  # POST /settlements.json
  def create
    @settlement = Settlement.new(settlement_params)

    respond_to do |format|
      if @settlement.save
        format.html { redirect_to @settlement, notice: 'Settlement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @settlement }
      else
        format.html { render action: 'new' }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settlements/1
  # PATCH/PUT /settlements/1.json
  def update
    respond_to do |format|
      if @settlement.update(settlement_params)
        format.html { redirect_to @settlement, notice: 'Settlement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settlements/1
  # DELETE /settlements/1.json
  def destroy
    @settlement.destroy
    respond_to do |format|
      format.html { redirect_to settlements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_settlement
      @settlement = Settlement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def settlement_params
      params.require(:settlement).permit(:icon, :color, :name, :language_id, :ancestry)
    end
end

app/helpers/settlements_helper.rb
module SettlementsHelper
end

app/views/settlements/_form.html.haml
= form_for @settlement do |f|
  - if @settlement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@settlement.errors.count, "error")} prohibited this settlement from being saved:"
      %ul
        - @settlement.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :icon
    = f.text_field :icon
  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :language_id
    = f.number_field :language_id
  .field
    = f.label :ancestry
    = f.text_field :ancestry
  .actions
    = f.submit 'Save'

app/views/settlements/edit.html.haml
%h1 Editing settlement

= render 'form'

= link_to 'Show', @settlement
\|
= link_to 'Back', settlements_path

app/views/settlements/index.html.haml
%h1 Listing settlements

%table
  %tr
    %th Icon
    %th Color
    %th Name
    %th Language
    %th Ancestry
    %th
    %th
    %th

  - @settlements.each do |settlement|
    %tr
      %td= settlement.icon
      %td= settlement.color
      %td= settlement.name
      %td= settlement.language_id
      %td= settlement.ancestry
      %td= link_to 'Show', settlement
      %td= link_to 'Edit', edit_settlement_path(settlement)
      %td= link_to 'Destroy', settlement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Settlement', new_settlement_path

app/views/settlements/new.html.haml
%h1 New settlement

= render 'form'

= link_to 'Back', settlements_path

app/views/settlements/show.html.haml
%p#notice= notice

%p
  %b Icon:
  = @settlement.icon
%p
  %b Color:
  = @settlement.color
%p
  %b Name:
  = @settlement.name
%p
  %b Language:
  = @settlement.language_id
%p
  %b Ancestry:
  = @settlement.ancestry

= link_to 'Edit', edit_settlement_path(@settlement)
\|
= link_to 'Back', settlements_path