config/routes.rb
Populinator::Application.routes.draw do

  devise_for :users
  resources :languages do
    resources :corpora
  end

  resources :settlements

  resources :beings

  root "welcome#index"
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :corpora
  accepts_nested_attributes_for :corpora, allow_destroy: true
  validates :lookback, presence: true
  validates :name, presence: true
  after_initialize do
    self.lookback = '2' if self.new_record?
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render action: 'show', status: :created, location: @language }
      else
        format.html { render action: 'new' }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:lookback, :name, :description, corpora_attributes: [:name, :url, :_destroy, :id])
    end

end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_corpus_fields.html.haml
.form-inputs
  = f.input :name, required: true
  = f.input :url, required: true
  %p.label
    destroy
    = f.check_box :_destroy

app/views/languages/_form.html.haml
= simple_form_for @language do |f|
  = f.error_notification
  .form-inputs
    = f.input :lookback, required: true, default: 2, hint: 'Larger lookback values cause the language to be more similar to the original corpus, smaller values make the language more random'
    = f.input :name, required: true
    = f.input :description
    .well
      =  f.simple_fields_for :corpora do |builder|
        = builder.input :name, required: true
        = builder.input :url, required: true
        = f.check_box :_destroy
      = link_to_add_fields "Add Corpus", f, :corpora
  .actions
    = f.submit 'Save'

app/views/languages/edit.html.haml
%h1 Editing language

= render 'form'

= link_to 'Show', @language
\|
= link_to 'Back', languages_path

app/views/languages/index.html.haml
%h1 Listing languages

%table
  %tr
    %th Lookback
    %th Description
    %th
    %th
    %th

  - @languages.each do |language|
    %tr
      %td= language.lookback
      %td= language.description
      %td= link_to 'Show', language
      %td= link_to 'Edit', edit_language_path(language)
      %td= link_to 'Destroy', language, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Language', new_language_path

app/views/languages/new.html.haml
%h1 New language

= render 'form'

= link_to 'Back', languages_path

app/views/languages/show.html.haml
%p#notice= notice

%p
  %b Lookback:
  = @language.lookback
%p
  %b Description:
  = @language.description

= link_to 'Edit', edit_language_path(@language)
\|
= link_to 'Back', languages_path