config/routes.rb
Populinator::Application.routes.draw do

  devise_for :users
  resources :languages do
    resources :corpora
  end

  resources :settlements

  resources :beings

  root "welcome#index"
end

app/models/being.rb
class Being < ActiveRecord::Base
end

app/controllers/beings_controller.rb
class BeingsController < ApplicationController
  before_action :set_being, only: [:show, :edit, :update, :destroy]

  # GET /beings
  # GET /beings.json
  def index
    @beings = Being.all
  end

  # GET /beings/1
  # GET /beings/1.json
  def show
  end

  # GET /beings/new
  def new
    @being = Being.new
  end

  # GET /beings/1/edit
  def edit
  end

  # POST /beings
  # POST /beings.json
  def create
    @being = Being.new(being_params)

    respond_to do |format|
      if @being.save
        format.html { redirect_to @being, notice: 'Being was successfully created.' }
        format.json { render action: 'show', status: :created, location: @being }
      else
        format.html { render action: 'new' }
        format.json { render json: @being.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beings/1
  # PATCH/PUT /beings/1.json
  def update
    respond_to do |format|
      if @being.update(being_params)
        format.html { redirect_to @being, notice: 'Being was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @being.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beings/1
  # DELETE /beings/1.json
  def destroy
    @being.destroy
    respond_to do |format|
      format.html { redirect_to beings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_being
      @being = Being.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def being_params
      params.require(:being).permit(:surname, :given_name, :age, :alive, :title, :gender, :ancestry)
    end
end

app/helpers/beings_helper.rb
module BeingsHelper
end

app/views/beings/_form.html.haml
= form_for @being do |f|
  - if @being.errors.any?
    #error_explanation
      %h2= "#{pluralize(@being.errors.count, "error")} prohibited this being from being saved:"
      %ul
        - @being.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :given_name
    = f.text_field :given_name
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :alive
    = f.check_box :alive
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :ancestry
    = f.text_field :ancestry
  .actions
    = f.submit 'Save'

app/views/beings/edit.html.haml
%h1 Editing being

= render 'form'

= link_to 'Show', @being
\|
= link_to 'Back', beings_path

app/views/beings/index.html.haml
%h1 Listing beings

%table
  %tr
    %th Surname
    %th Given name
    %th Age
    %th Alive
    %th Title
    %th Gender
    %th Ancestry
    %th
    %th
    %th

  - @beings.each do |being|
    %tr
      %td= being.surname
      %td= being.given_name
      %td= being.age
      %td= being.alive
      %td= being.title
      %td= being.gender
      %td= being.ancestry
      %td= link_to 'Show', being
      %td= link_to 'Edit', edit_being_path(being)
      %td= link_to 'Destroy', being, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Being', new_being_path

app/views/beings/new.html.haml
%h1 New being

= render 'form'

= link_to 'Back', beings_path

app/views/beings/show.html.haml
%p#notice= notice

%p
  %b Surname:
  = @being.surname
%p
  %b Given name:
  = @being.given_name
%p
  %b Age:
  = @being.age
%p
  %b Alive:
  = @being.alive
%p
  %b Title:
  = @being.title
%p
  %b Gender:
  = @being.gender
%p
  %b Ancestry:
  = @being.ancestry

= link_to 'Edit', edit_being_path(@being)
\|
= link_to 'Back', beings_path