config/routes.rb
Populinator::Application.routes.draw do

  devise_for :users
  resources :languages do
    resources :corpora
  end

  resources :settlements

  resources :beings

  root "welcome#index"
end

app/controllers/corpora_controller.rb
class CorporaController < ApplicationController
  before_action :set_corpus, only: [:show, :edit, :update, :destroy]

  # GET /corpora
  # GET /corpora.json
  def index
    @corpora = Corpus.all
  end

  # GET /corpora/1
  # GET /corpora/1.json
  def show
  end

  # GET /corpora/new
  def new
    @corpus = Corpus.new
  end

  # GET /corpora/1/edit
  def edit
  end

  # POST /corpora
  # POST /corpora.json
  def create
    @corpus = Corpus.new(corpus_params)

    respond_to do |format|
      if @corpus.save
        format.html { redirect_to @corpus, notice: 'Corpus was successfully created.' }
        format.json { render action: 'show', status: :created, location: @corpus }
      else
        format.html { render action: 'new' }
        format.json { render json: @corpus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corpora/1
  # PATCH/PUT /corpora/1.json
  def update
    respond_to do |format|
      if @corpus.update(corpus_params)
        format.html { redirect_to @corpus, notice: 'Corpus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @corpus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corpora/1
  # DELETE /corpora/1.json
  def destroy
    @corpus.destroy
    respond_to do |format|
      format.html { redirect_to corpora_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corpus
      @corpus = Corpus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corpus_params
      params.require(:corpus).permit(:language_id, :name, :url)
    end
end

app/helpers/corpora_helper.rb
module CorporaHelper
end

app/views/corpora/_form.html.haml
= simple_form_for(@corpus) do |f|
  = f.error_notification

  .form-inputs
    = f.input :language_id
    = f.input :name
    = f.input :url

  .form-actions
    = f.button :submit

app/views/corpora/edit.html.haml
%h1 Editing corpus

= render 'form'

= link_to 'Show', @corpus
\|
= link_to 'Back', corpora_path

app/views/corpora/index.html.haml
%h1 Listing corpora

%table
  %tr
    %th Language
    %th Name
    %th Url
    %th
    %th
    %th

  - @corpora.each do |corpus|
    %tr
      %td= corpus.language_id
      %td= corpus.name
      %td= corpus.url
      %td= link_to 'Show', corpus
      %td= link_to 'Edit', edit_corpus_path(corpus)
      %td= link_to 'Destroy', corpus, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Corpus', new_corpus_path

app/views/corpora/new.html.haml
%h1 New corpus

= render 'form'

= link_to 'Back', corpora_path

app/views/corpora/show.html.haml
%p#notice= notice

%p
  %b Language:
  = @corpus.language_id
%p
  %b Name:
  = @corpus.name
%p
  %b Url:
  = @corpus.url

= link_to 'Edit', edit_corpus_path(@corpus)
\|
= link_to 'Back', corpora_path